version: "3.1"
services:
  wordpress:
    image: wordpress
    restart: always
    container_name: "wpsite"
    ports:
      - 5050:80
    volumes:
      - ~/git/projetox/wpsite:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: senac
      WORDPRESS_DB_PASSWORD: senac@123
      WORDPRESS_DB_NAME: projetodb

  db:
    image: mysql:8.0
    restart: always
    container_name: "wpdados"
    environment:
      MYSQL_DATABASE: projetodb
      MYSQL_USER: senac
      MYSQL_PASSWORD: senac@123
      MYSQL_ROOT_PASSWORD: senac@123
    ports:
      - 4040:3306
    volumes:
      - ~/git/projetox/wpdados:/var/lib/mysql
